title: Fulcrum Wiki
description: Fulcrum Wiki is a public wiki providing resources to learn about the impact ecnonomy.
show_downloads: true
git_branch: master
logo_url:
google_analytics:
theme:
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token:
custom_head: false
custom_sidebar: false
custom_footer: false
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
